pbTests: Add option to build Hotspot; Add options to specify build repo
AdoptOpenJDK/openjdk-infrastructure pull request #1533
Opened 2020-09-07 10:30 UTC by Willsparker

I realised that these options were missing from `QPC.sh`, despite `buildJDK.sh` having the functionality to do those things, so I thought I'd add them in.

Testing at : https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/92/ARCHITECTURE=arm32,label=vagrant/console

(I will make ready to review once I've ensured the above run will start a Hotspot JDK build)

2020-09-07 14:16 UTC, Haroon-Khel commented
I havent yet made a pr for the gcc7/g++7 debain changes yet, it only exists on the gcc.arm32 branch on my fork currently while it is being tested. When the above build passes, ill submit a pr for it.

2020-09-07 17:45 UTC, sxa requested changes
Can we make this use `--build-hotspot` for consistency with the parameter in vagrantPlaybookCheck?

2020-09-08 08:11 UTC, Willsparker commented
@Haroon-Khel It passed! :grin:

2020-09-09 10:12 UTC, sxa approved these changes

2020-09-09 10:38 UTC, merged