unixPB/winPB: Add JDK15 for bootstrapping JDK16
AdoptOpenJDK/openjdk-infrastructure pull request #1639
Opened 2020-10-20 12:37 UTC by sxa

Replace JDK13 (since 14 is out of support) with JDK15 used for bootstrapping JDK16

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2020-10-20 12:38 UTC, sxa commented
Testing queued up at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/906/

2020-10-20 12:44 UTC, karianna approved these changes
lgtm

2020-10-20 15:57 UTC, sxa commented
Post GA, this fixes https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1635 so it won't need to be dynamically downloaded anyway, which will speed things by skipping that step :-)

2020-10-21 12:41 UTC, Willsparker approved these changes
LGTM

2020-10-21 12:42 UTC, Willsparker requested changes
Oh wait, you didn't add JDK15 to the Windows PB - just Unix

2020-10-21 16:12 UTC, sxa commented
@Willsparker Where do you pass in the directory for the boot JDKs? It doesn't look like https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Debian10,label=vagrant/906/consoleFull found the ansible-installed JDK15 from this PR
```
17:04:08 SCM_REF: 
17:04:08 Detecting boot jdk for: jdk
17:04:08 Found build version: 16
17:04:08 Required boot JDK version: 15
17:04:08 Downloading GA release of boot JDK version 15...
17:04:28 openjdk version "15" 2020-09-15
17:04:28 OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
17:04:28 Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.22.0, JRE 15 Linux amd64-64-Bit Compressed References 20200922_46 (JIT enabled, AOT enabled)
17:04:28 OpenJ9   - 1830b1927
17:04:28 OMR      - 73d5e7623
17:04:28 JCL      - 7e7613c015 based on jdk-15+36)
```

2020-10-21 16:14 UTC, sxa commented
> Oh wait, you didn't add JDK15 to the Windows PB - just Unix

Fixed - I'd made the change on my local FS but not added it to the PR - good spot!

2020-10-22 09:05 UTC, Willsparker commented
@sxa The debug output said it did set `JDK_BOOT_DIR` to `/usr/lib/jvm/jdk-15`, which Is where it should be. Your VPC run (911) confirms this :-) Could it be that the build scripts just download the boot JDK, irrespective of if the boot JDK is already on the machine or not?

2020-10-22 09:42 UTC, sxa commented
No, the production builds do not do that e.g. [this one](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/768/consoleFull):
```
00:41:11  Boot jdk directory: /usr/lib/jvm/jdk-10:
00:41:11  BOOT JDK: openjdk version "10.0.2" 2018-07-17
00:41:11  BOOT JDK: OpenJDK Runtime Environment AdoptOpenJDK (build 10.0.2+13)
00:41:11  BOOT JDK: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 10.0.2+13, mixed mode)
```

2020-10-22 12:24 UTC, sxa commented
Reviewers note: Ignoring whitespace change this is a removal of this check:
```
   if [ "$JAVA_FEATURE_VERSION" -gt 11 ]; then
```
which I don't believe is still needed and the addition of this code to default `JDKxx_BOOT_DIR` if it is not defined on the jenkins agent (Note that the initial check now looks for `javac` instead of just the `bin` directory as that's a bit safer)
```
    if [ ! -x "$bootDir/bin/javac" ]; then
      # Set to a default location as linked in the ansible playbooks
      if [ -x /usr/lib/jvm/jdk-${BOOT_JDK_VERSION}/bin/javac ]; then
        echo Could not use ${BOOT_JDK_VARIABLE} - using /usr/lib/jvm/jdk-${BOOT_JDK_VERSION}
        export ${BOOT_JDK_VARIABLE}="/usr/lib/jvm/jdk-${BOOT_JDK_VERSION}"
      else
```
If this proves to be safe (and it looks good so far based on [this VPC run](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/914/) - FYI @Willsparker as this works around the fact the VPC scripts aren't picking up the installed boot JDKs) I'll look at adding similar logic to OSs other than Linux

Note that this detection will NOT work for java7 or java 8 since the directory names are currently `jdk8` (Without the `-`) as per comments in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1138#issuecomment-585178069 and `zulu7` on some platforms for the V7 JDKs

2020-10-23 08:21 UTC, Willsparker commented
> No, the production builds do not do that

Hmm, good point, I'll look at that today then!

2020-10-23 08:35 UTC, Willsparker approved these changes
LGTM :+1:

2020-12-10 15:57 UTC, Haroon-Khel commented
Is there still work to be done on this pr? Or can it be merged?

2020-12-10 22:19 UTC, karianna commented
conflicts

2020-12-24 16:33 UTC, closed without merging