Add issue and PR templates to the repository
AdoptOpenJDK/openjdk-infrastructure pull request #1650
Opened 2020-10-26 15:22 UTC by sxa

I've been meaning to do this for a while. Add an initial set of issue and PR templates fo the repository to make it easier for people submitting issues/PRs to have them categorised correctly and supply all relevant information. We can update/refine as we go on (and see which issues don't fit into these!)

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2020-10-26 18:07 UTC, gdams approved these changes

2020-10-27 08:10 UTC, Willsparker requested changes

2020-10-27 08:10 UTC, Willsparker commented on .github/ISSUE_TEMPLATE/ansible.md
> +Please put the name of the software product (and affectred platforms if relevant) in the title of this issue
```suggestion
Please put the name of the software product (and affected platforms if relevant) in the title of this issue
```

2020-10-27 10:40 UTC, Willsparker approved these changes

2020-10-27 11:32 UTC, merged