Ansible: refresh macOS test machines + playbook patches
AdoptOpenJDK/openjdk-infrastructure pull request #1665
Opened 2020-11-03 16:31 UTC by gdams

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] inventory changes, ensure bastillion is updated accordingly

2020-11-03 18:12 UTC, karianna commented
Linter fixes needed.

2020-11-08 15:11 UTC, karianna commented
```
TASK [Common : Upgrade installed packages] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Updating Homebrew...\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nError: Could not remove ansible keg! Do so manually:\n  sudo rm -rf /usr/local/Cellar/ansible/2.9.13_1"}
```

2020-11-16 12:22 UTC, sxa commented
Is there any reason these cannot be added to Bastillion (as per the last checkbox)?

2020-11-16 17:32 UTC, Haroon-Khel requested changes

2020-11-16 17:32 UTC, Haroon-Khel commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml
> +
`jenkins` and `adoptopenjdk` tags on this task would be appropriate

2020-11-16 17:35 UTC, Haroon-Khel commented
The changes made to the inventory file would put it in sync with the machines listed in Jenkins, as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1675, so Im all for that. 

However, I do not have a fresh mac os machine on which to test out the ansible changes

2020-11-24 10:13 UTC, gdams commented
@Haroon-Khel updated PTAL

2020-11-24 13:49 UTC, karianna commented
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Updating Homebrew...\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nNo entry for terminal type \"unknown\";\nusing dumb terminal settings.\nError: Could not remove ansible keg! Do so manually:\n  sudo rm -rf /usr/local/Cellar/ansible/2.9.15"}

2020-11-25 16:26 UTC, gdams commented
> Is there any reason these cannot be added to Bastillion (as per the last checkbox)?

@sxa I've now added all macs from the inventory file into Bastillion 🎉

2020-12-03 10:43 UTC, karianna commented
run tests

2020-12-03 12:48 UTC, Haroon-Khel approved these changes
The ansible additions look good to me, they pass on the macos check. The new Xcode10 role doesnt run on the macos check, since it skips roles tagged with `adoptopenjdk`, but @gdams confirms that he has tested it and it works. Same goes for the macos_codesign role.

2020-12-03 12:50 UTC, merged