Remove packages already installed by yum
AdoptOpenJDK/openjdk-infrastructure pull request #1704
Opened 2020-11-24 13:16 UTC by aixtools

##### Checklist

- [ x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)

The playbook includes packages not available, directly, using yum. RPM's previously not available, are now available and need to be removed from the 'additional' packages list.

2020-11-26 17:29 UTC, Haroon-Khel commented
Received an unfamilar error when running the yum role

```
TASK [Install yum and dependencies] *****************************************************************************************************************************************************************************************************************************************************
task path: /Users/hkhel/AdoptOpenJDK/openjdk-infrastructure/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml:34
fatal: [p9-aix1-ojdk06.osuosl.org]: FAILED! => {"msg": "Invalid variable name in 'register' specified: 'result.yum'"}
```

2020-11-26 17:33 UTC, Haroon-Khel commented
Also, the yum role as one of the first roles, as it installs unzip and tar, both needed for the x11, xlc13 and xlc16 roles (and any other which involves decompressing and unzipping packages). The change would be more suitable in your other [pr](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1695)

2020-11-27 16:59 UTC, aixtools commented
> 
> 
> Also, I believe the yum role should run as one of the first roles, as it installs unzip and tar, both needed for the x11, xlc13 and xlc16 roles (and any other which involves decompressing and unzipping packages). The change would be more suitable in your other [pr](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1695)

Looking at xlc13 - the vendor file is packed using gzip, not unzip - and depending on module logic AIX gzip and tar are fine for unpacking. If unarchive: `demands` GNU zip then a `shell:` command such as `gzip -dc {{ filename }} | ( cd /tmp; tar xf -)`

Note: read unarchive Ansible module: states it requires zipinfo, unzip and gtar.

This could be rewritten to use shell: and remove the module requirements.

2020-11-30 16:17 UTC, Haroon-Khel requested changes

2020-11-30 16:17 UTC, Haroon-Khel commented on ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/yum/tasks/main.yml
>    tags: rpm_install
Could you add yum tags to this task and the one below it please. The proper syntax is 
```
  tags: 
    - rpm_install
    - yum
```

2020-12-02 10:47 UTC, Haroon-Khel commented
@aixtools (same as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1695) this pr is ready to be merged (after the requested changes have been put in)

2020-12-03 16:30 UTC, Haroon-Khel approved these changes
LGTM

2020-12-04 10:20 UTC, aixtools commented
thx @Haroon-Khel

2020-12-04 11:15 UTC, merged