pbTests: switch mirrorlist to vault on centOS6 yum repo
AdoptOpenJDK/openjdk-infrastructure pull request #1756
Opened 2020-12-09 19:00 UTC by sxa

This should fix the yum problem on CentOS6 in VPC ...

Draft while
- I verify that it works ok
- I decide whether this is the right place to do it instead of the playbooks (it probably isn't)

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] FAQ.md updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) - https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/964/
- [ ] inventory changes, ensure bastillion is updated accordingly

2020-12-10 21:37 UTC, karianna approved these changes
lgtm

2020-12-14 11:25 UTC, Willsparker requested changes
From VPC : 
```
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
20:17:45     adoptopenjdkC6:  Eg. </body></html>/
20:17:45     adoptopenjdkC6: removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
20:17:45     adoptopenjdkC6: Error: Cannot find a valid baseurl for repo: base
```

2020-12-15 19:42 UTC, karianna commented
@Willsparker since Stewart is away, can you take this PR over?

2020-12-15 21:42 UTC, Willsparker commented
Sure :-)

2020-12-16 18:43 UTC, Willsparker commented
Closing in favour of #1765

2020-12-16 18:43 UTC, closed without merging