Inventory: add alibaba machines
AdoptOpenJDK/openjdk-infrastructure pull request #1774
Opened 2020-12-21 12:04 UTC by Haroon-Khel

Added the machines build-alibaba-win2012r2-x64-1 and 2 to the inventory file. They are already in jenkins

- [ ] inventory changes, ensure bastillion is updated accordingly

@sxa Bastillion will need to be updated, if it already hasnt been

2020-12-21 12:22 UTC, sxa approved these changes
Bastillion only manages the UNIX-based systems, so this is good to land :-)

2020-12-21 12:24 UTC, sxa requested changes
Actually I'm going to reject this until the linter runs clean ... since alibaba is a new provider in here `./plugins/inventory/adoptopenjdk_yaml.py` will need to be updated to have it in the `provider` list

2020-12-22 10:39 UTC, Willsparker approved these changes
LGTM

2020-12-22 19:07 UTC, sxa approved these changes

2020-12-22 19:11 UTC, merged