inv: Correct Node name mistakes
AdoptOpenJDK/openjdk-infrastructure pull request #1806
Opened 2021-01-06 10:18 UTC by Willsparker

ref: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1716#issuecomment-755202080

- [x] inventory changes, ensure bastillion is updated accordingly

Just some mistakes I noticed whilst going through the list of machines that need to be added to Nagios. As these are inconsistent with the node names in Jenkins, my Nagios check (#1717) is unable to find them. I opted for changing the inventory entry as this is easier than renaming the node in Jenkins :-)

2021-01-06 10:36 UTC, sxa requested changes
this change to add the `l` onto a subset of the arm systems makes the naming inconsistent as many are still left as `armv8` / `armv7`, so I would suggest we need to change the definitions elsewhere.

2021-01-06 13:14 UTC, Willsparker commented
I'll take that out - we should probably change it in Jenkins then :-)

2021-01-06 14:44 UTC, karianna approved these changes
lgtm

2021-01-14 17:33 UTC, sxa approved these changes

2021-01-14 17:33 UTC, merged