docs: Add note about needing ITW to run Jenkins Agent
AdoptOpenJDK/openjdk-infrastructure pull request #1825
Opened 2021-01-11 10:49 UTC by Willsparker

ref: #1773 , https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1610356948467700, #1818 

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [x] other documentation is changed or added (if applicable)

Adding a note that IcedTea-Web is needed to run `.jnlp` files- It's tripped me up, and it has other people as well, so I feel it's necessary to mention.

2021-01-11 11:21 UTC, sxa requested changes
Suggestion to improve references for those who aren't familiar with ITW

2021-01-11 11:21 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md
> +4) On the machine, in a web browser, login to [ci.adoptopenjdk.net](https://ci.adoptopenjdk.net/), create a new node and download/run the `slave-agent.jnlp`. IcedTea-Web will need to be installed to
```suggestion
4) On the machine, in a web browser, login to [ci.adoptopenjdk.net](https://ci.adoptopenjdk.net/), create a new node and download/run the `slave-agent.jnlp`. [IcedTea-Web](https://adoptopenjdk.net/icedtea-web.html) (or another `javaws` implementation) will need to be installed to run the `.jnlp` file.
```

2021-01-11 11:48 UTC, Willsparker commented on ansible/playbooks/AdoptOpenJDK_Windows_Playbook/README.md
> +4) On the machine, in a web browser, login to [ci.adoptopenjdk.net](https://ci.adoptopenjdk.net/), create a new node and download/run the `slave-agent.jnlp`. IcedTea-Web will need to be installed to
Commited, thanks :+1:

2021-01-12 12:55 UTC, karianna approved these changes
lgtm

2021-01-12 13:01 UTC, Haroon-Khel approved these changes
LGTM

2021-01-14 16:19 UTC, sxa approved these changes

2021-01-14 16:19 UTC, merged