UnixPB: Temporarily fix CentOS6 Adoptopenjdk_install role
AdoptOpenJDK/openjdk-infrastructure pull request #1913
Opened 2021-02-09 09:30 UTC by Willsparker

ref: #1877 

This is a temporary fix, to get the Docker C6 and VPC checks working for now- given that the requests are to our API server, I'm less scared about not validating those certs.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate : N/A
- [ ] other documentation is changed or added (if applicable) : N/A
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) : https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1012/console
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly : N/A

2021-02-09 09:31 UTC, Willsparker commented
Note: Don't want to merge this until specifically @sxa has seen / reviewed this

2021-02-10 16:42 UTC, karianna commented
> Note: Don't want to merge this until specifically @sxa has seen / reviewed this

Doesn't look it worked?

2021-02-10 17:02 UTC, sxa requested changes
This says "Temporarily" ... Does that mean there's a plan to have a proper fix somewhere? I really don't want to leave anything like this in place ...

2021-02-10 17:02 UTC, sxa commented on ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml
> +# Currenlty not checking certs due to a CentOS6 error
```suggestion
# Currently not checking certs due to a CentOS6 error
```

2021-02-11 09:09 UTC, Willsparker commented
> Doesn't look it worked? 

The check look like it failed when building the docker image .. The playbook should be fixed with this PR, but I'll look at that issue next :-) 

> This says "Temporarily" ... Does that mean there's a plan to have a proper fix somewhere? I really don't want to leave anything like this in place ...

I'll continue working on it - the initial thought was to have CentOS6 update Python to 2.7.9 at the beginning of the playbook, but that causes extra issues. What I've tried is in the referenced issue

2021-02-11 09:31 UTC, Willsparker commented
Converting to Draft as I figure out the Dockerfile issue

2021-02-11 10:24 UTC, Willsparker commented
Looks like upgrading pip has fixed the Dockerfile issue. I'm not sure why the Ansible_Lint check is failing - it seems to not like `ansible/playbooks/adoptopenjdk_variables.yml` for some reason.

2021-02-12 16:17 UTC, sxa commented
ansible-lint failure has been raised https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1926 as it's not just affecting this PR, so do not consider that a blocker.

2021-02-16 16:35 UTC, sxa commented
NOTE TO REVIEWERS: Discussion currently continuing in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1877

2021-02-16 16:37 UTC, karianna commented
@sxa should we put this in draft?

2021-02-23 09:46 UTC, Willsparker commented
Closing as #1970 is better

2021-02-23 09:46 UTC, closed without merging