unixPB: Install Python2.7 on C6; Use it to install JDKs
AdoptOpenJDK/openjdk-infrastructure pull request #1970
Opened 2021-02-23 09:45 UTC by Willsparker

Fixes: #1877 

IT WORKS! (in VPC at least: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1067/ )

Installs Python 2.7 on CentOS6 and then uses that Python to run the `adoptopenjdk_install` tasks. See the referenced issue for what other things were tried or suggested. This solution also adds some future proofing somewhat, in that we can just use the Python2.7 whenever we have another `unarchive` / `get_url` cert issue because CentOS6 is old.

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) : See above
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-02-23 12:04 UTC, sxa reviewed
How long does this role to execute? Could be preferable to use the pre-built one I put in place last week instead which would also avoid having to install the extra prereq packages on the machine.

2021-02-23 12:20 UTC, karianna requested changes
Fix YAMLLint please :-)

2021-02-24 08:41 UTC, Willsparker commented
> How long does this role to execute? Could be preferable to use the pre-built one I put in place last week instead which would also avoid having to install the extra prereq packages on the machine.

About 10 minutes in VPC , not sure on the GHCheck as it doesn't have timestamps. But yeah, okay, I'll try prebuilt :-)

2021-02-24 09:50 UTC, karianna approved these changes

2021-02-24 09:55 UTC, Willsparker commented
Well it works! :tada:

2021-02-24 10:43 UTC, gdams approved these changes

2021-02-24 11:35 UTC, merged