vagrant: add win2016 support and action
AdoptOpenJDK/openjdk-infrastructure pull request #2003
Opened 2021-03-04 16:39 UTC by gdams

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-03-08 07:14 UTC, Willsparker commented
Judging from the check, it looks like this is required for 2016 as well:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/07ec26d21f70b810dbc0589b3d3b3ee01de5adf7/ansible/Vagrantfile.Win2012#L12

2021-03-10 07:19 UTC, Willsparker commented
Ref: The `become` issue: https://groups.google.com/g/ansible-project/c/r52FeZLjttI?pli=1

It's weird that you'd need to specify `runAs`, considering we don't do that for 2012r2. 
One other thing I'd mention - the playbook appears to be running on every single port that the VM has opened, however, it should just need `55986` (the last port number given when running `vagrant port`).

2021-03-17 19:54 UTC, karianna commented
```
TASK [Gathering Facts] *********************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The powershell shell family is incompatible with the sudo become plugin"}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Error: Process completed with exit code 2.
```

2021-03-18 08:08 UTC, Willsparker requested changes

2021-03-18 08:08 UTC, Willsparker commented on .github/workflows/build_vagrant_win.yml
> +        ansible-playbook -i playbooks/AdoptOpenJDK_Windows_Playbook/hosts.win -u vagrant -b --skip-tags adoptopenjdk playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
```suggestion
        ansible-playbook -i playbooks/AdoptOpenJDK_Windows_Playbook/hosts.win -u administrator --skip-tags adoptopenjdk playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
```
Had a quick check, the Administrator account has the same password as the vagrant account (i.e. `vagrant`), and stops the need for the `-b` tag, that's causing an issue :-)

2021-03-24 07:55 UTC, Willsparker reviewed
LGTM, in terms of code - The GHCheck has still failed, with an error I see fairly often in VPC. I'm somewhat concerned to have this as a GHCheck due to this instability of it

2021-03-24 09:33 UTC, gdams commented
@Willsparker removed the GH action

2021-03-24 11:48 UTC, Willsparker approved these changes
LGTM - I'm not entirely against adding it in the future - I'm looking at what could make the win2012r2 VF buggy in VPC now with #2056 , so we may be able to apply those changes / Fixes to 2016 too

2021-03-24 11:59 UTC, merged