unixPB/winPB: Add ansible_version to debug info
AdoptOpenJDK/openjdk-infrastructure pull request #2047
Opened 2021-03-17 13:38 UTC by sxa

Print `ansible_version` into the logs for debugging purposes

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [x] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access) - [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1112)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-03-18 09:15 UTC, Willsparker requested changes
Would you mind making this print only the `.full`, as (looking at [VPC](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1113/OS=Debian8,label=vagrant/console)), there's a lot of duplicated output:
```
"ansible_version: {'major': 2, 'full': '2.9.16', 'string': '2.9.16', 'minor': 9, 'revision': 16} ", 
```

2021-03-19 09:01 UTC, Willsparker approved these changes

2021-03-19 10:27 UTC, sxa commented
@Willsparker ARGH! The Windows VPC is sooooooo unstable. But I'm happy with this so I'll merge.

2021-03-19 10:28 UTC, merged

2021-03-19 10:41 UTC, Willsparker commented
> ARGH! The Windows VPC is sooooooo unstable.

https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2056
Haven't assigned myself yet until I'm out of the depths of coursework hell, next week, and I can commit more time.