Add a little more info to the Jenkins backup and fix lots of Markdown Linter issues
AdoptOpenJDK/openjdk-infrastructure pull request #2077
Opened 2021-03-24 11:18 UTC by karianna

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-03-24 12:03 UTC, Willsparker requested changes

2021-03-24 12:03 UTC, Willsparker commented on README.md
> +|---|---|---|---|
In the Rich Text Display, this table isn't being shown as a table. I think it may be because you need an extra `---|`

2021-03-24 12:26 UTC, tellison requested changes

2021-03-24 12:26 UTC, tellison commented on README.md
> +|---|---|---|---|
```suggestion
|---|---|---|---|---|
```
Agree with Will

2021-04-09 08:16 UTC, Willsparker requested changes
Just some other changes found on a second pass through :-)

2021-04-09 08:16 UTC, Willsparker commented on FAQ.md
>  .the various `playlist.xml` files in the test repositories. It can also be
```suggestion
 the various `playlist.xml` files in the test repositories. It can also be
```
Stray full stop

2021-04-09 08:16 UTC, Willsparker commented on ansible/README.md
> +```sh
```suggestion
```log
```
As it's Ansible output

2021-04-13 17:01 UTC, karianna commented
Again, rebase ruined this PR.  Clearly I'm using Git incorrectly.  I won't have time to resolve this so closing the PR.

2021-04-13 17:01 UTC, closed without merging