pbTests: Log console output of QEMU VM on first boot
AdoptOpenJDK/openjdk-infrastructure pull request #2088
Opened 2021-03-28 12:46 UTC by sxa

No reason to hide the logs - it can assist with debugging if the machine hasn't started for some reason

##### Checklist

- [ ] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-03-30 07:44 UTC, Willsparker commented
Testing at: https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/222/console
The job has to be reconfigured to test your branch, so I'll try remember to put it back afterwards :-)

2021-03-30 07:57 UTC, Willsparker requested changes
The stuff I saw from the QPC run. I will note, that despite the `${ARCHITEFCTURE}`, the log was _there_ in the place it said it was, so it's doing it's job, it just wasn't output due to the `;` in the `sed` command :-)

2021-03-30 07:57 UTC, Willsparker commented on ansible/pbTestScripts/qemuPlaybookCheck.sh
> +	echo "Machine is booting; logging console to $workFolder/${OS}.${ARCHITEFCTURE}.startlog Please be patient"
```suggestion
	echo "Machine is booting; logging console to $workFolder/${OS}.${ARCHITECTURE}.startlog Please be patient"
```

2021-03-30 07:57 UTC, Willsparker commented on ansible/pbTestScripts/qemuPlaybookCheck.sh
> +	tail "$workFolder/${OS}.${ARCHITEFCTURE}.startlog" | sed ;s/^/CONSOLE > /g'
```suggestion
	tail "$workFolder/${OS}.${ARCHITECTURE}.startlog" | sed 's/^/CONSOLE > /g'
```

2021-03-30 07:57 UTC, Willsparker commented on ansible/pbTestScripts/qemuPlaybookCheck.sh
> +	  -nographic) > "$workFolder/${OS}.${ARCHITEFCTURE}.startlog" 2>&1 &
```suggestion
	  -nographic) > "$workFolder/${OS}.${ARCHITECTURE}.startlog" 2>&1 &
```

2021-04-01 08:59 UTC, Willsparker commented
Rerunning now : https://ci.adoptopenjdk.net/job/QEMUPlaybookCheck/225/

2021-04-01 11:22 UTC, sxa commented
LGTM - Console log appearing where it is supposed to :-)

2021-04-06 06:20 UTC, Willsparker approved these changes
LGTM :-)

2021-04-07 18:17 UTC, merged