docs: Update FAQ with information on DockerStatic containers
AdoptOpenJDK/openjdk-infrastructure pull request #2148
Opened 2021-04-20 15:19 UTC by sxa

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [x] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-04-21 09:27 UTC, Haroon-Khel approved these changes
LGTM. Couldnt find an error 👍🏻

2021-04-26 07:06 UTC, Willsparker requested changes
Otherwise, LGTM

2021-04-26 07:06 UTC, Willsparker commented on FAQ.md
> +in jenkins should list which host it's on, but can you also look up the
```suggestion
in jenkins should list which host it's on, but you can also look up the
```
Mismatched words

2021-04-28 13:43 UTC, karianna approved these changes
LGTM

2021-04-28 14:06 UTC, Willsparker approved these changes
LGTM

2021-04-28 15:34 UTC, merged