inventory: Remove two OSUOSL Ubuntu 16.04 hosts
AdoptOpenJDK/openjdk-infrastructure pull request #2150
Opened 2021-04-21 16:39 UTC by sxa

Signed-off-by: Stewart X Addison <sxa@redhat.com>

##### Checklist

- [x] commit message has one of the [standard prefixes](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/CONTRIBUTING.md#commit-messages)
- [ ] [FAQ.md](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/FAQ.md) updated if appropriate
- [ ] other documentation is changed or added (if applicable)
- [ ] playbook changes run through [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) or [QPC](https://ci.adoptopenjdk.net/view/Tooling/job/QEMUPlaybookCheck/) (if you have access)
- [ ] for inventory.yml changes, bastillion/nagios/jenkins updated accordingly

2021-04-26 07:40 UTC, gdams approved these changes

2021-04-27 08:18 UTC, Willsparker requested changes
This is being done as part of #2156  (I know that PR is newer, but I suppose it'd better to do inventory changes in one big swoop)

2021-04-27 08:37 UTC, sxa commented
> This is being done as part of #2156 (I know that PR is newer, but I suppose it'd better to do inventory changes in one big swoop)

Doesn't make a lot of difference. These ones had been removed a while ago so was a differnet batch

2021-04-27 08:40 UTC, Willsparker approved these changes
Fair enough. I was unsure if this merging would cause a merge conflict in the later PR, so closing this would avoid that :shrug:

2021-04-27 16:48 UTC, merged